name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          submodules: true

      - name: Install and Build
        run: |
          npm install
          npm run compile

      - name: Prune Dev Dependencies
        run: |
          npm install
          npm prune --production

      - name: Prune NPX Binaries
        run: rm -r node_modules/.bin

      - name: Copy Dependencies
        run: |
          cp -r node_modules dist/node_modules

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: dist
          FOLDER: dist
          CLEAN: true
